### ISSUE TITLE
Generated datetimes are not valid according to FHIR R4

### ISSUE THREAD

**Issue by ibmatc** [LinuxForHealth/hl7v2-fhir-converter#55]
The date times generated by the converter are not valid according to the $validate API in FHIR.  I used:

[hl7_input.txt](https://github.com/LinuxForHealth/hl7v2-fhir-converter/files/5984296/hl7_input.txt)
which I got from here: https://raw.githubusercontent.com/LinuxForHealth/hl7v2-fhir-converter/master/src/test/resources/sample_win.hl7

This produced this FHIR data:
[hl7_produced_fhir.txt](https://github.com/LinuxForHealth/hl7v2-fhir-converter/files/5984304/hl7_produced_fhir.txt)

which contains the datetime value of "2014-09-12T22:00:00"

When this FHIR bundle is sent to a FHIR R4 server using the $validate API, the following error is reported:

[fhir_validate_message.txt](https://github.com/LinuxForHealth/hl7v2-fhir-converter/files/5984303/fhir_validate_message.txt)

**Comment by pbhallam** [comment]
According to FHIR specs:
dateTime	A date, date-time or partial date (e.g. just year or year + month) as used in human communication. The format is YYYY, YYYY-MM, YYYY-MM-DD or YYYY-MM-DDThh:mm:ss+zz:zz, e.g. 2018, 1973-06, 1905-08-23, 2015-02-07T13:28:17-05:00 or 2017-01-01T00:00:00.000Z. If hours and minutes are specified, a time zone SHALL be populated. Seconds must be provided due to schema type constraints but may be zero-filled and may be ignored at receiver discretion. Dates SHALL be valid dates. The time "24:00" is not allowed. Leap Seconds are allowed - see below
https://www.hl7.org/fhir/datatypes.html#dateTime

So the date that failed validation is missing zone information. That is because  the input information is without zone PV1|1|ff|yyy|EL|ABC||200^ATTEND_DOC_FAMILY_TEST^ATTEND_DOC_GIVEN_TEST|201^REFER_DOC_FAMILY_TEST^REFER_DOC_GIVEN_TEST|202^CONSULTING_DOC_FAMILY_TEST^CONSULTING_DOC_GIVEN_TEST|MED|||||B6|E|272^ADMITTING_DOC_FAMILY_TEST^ADMITTING_DOC_GIVEN_TEST||48390|||||||||||||||||||||||||201409122200|

one option would be to ignore such dates but in that case we might end up missing lot of information as for HL7 it is valid to not include zone information.

Another option is to send default zone during conversion , so for any date without zone information from HL7 will assume the passed zone information.

**Comment by pbhallam** [comment]
Merged changes .
